modLoader = "javafml"
loaderVersion = "[47,)"
license = "${mod_license}"
issueTrackerURL = "https://github.com/Blazelow/Dawn-of-Time-Extra-Additions/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/dawn-of-time-extra-additions"
authors = "${mod_author}"
credits = "${mod_credits}"
description = '''${mod_description}'''
logoFile = "icon.png"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[47.2.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "dawnoftimebuilder"
mandatory = true
versionRange = "[1.5.53,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "fusion"
mandatory = false
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "CLIENT"
