org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=false
org.gradle.daemon=true
org.gradle.configuration-cache=false

# Mod
mod_id=dawnoftimeextras
mod_name=Dawn of Time: Extra Additions
mod_version=1.0.0
mod_group_id=com.blazelow.dawnoftimeextras
mod_author=Blazelow
mod_license=MIT
mod_description=Dawn of Time: Extra Additions is a large building and decoration expansion for Dawn of Time, adding a wide variety of new blocks, architectural pieces, furniture, decorative variants, custom signs, and material extensions designed to fit naturally into the Dawn of Time style.

# Minecraft
minecraft_version=1.21.1

# Fabric
fabric_loader_version=0.16.14
fabric_api_version=0.116.17+1.21.1

# NeoForge
neo_version=21.1.172

# Dawn Of Time 1.6.6 on Modrinth (maven.modrinth:dawn-of-time:<version id>), compile-time only
dot_fabric_version=fUx53G6d
dot_neoforge_version=fo9df0lp
